### ISSUE TITLE
Design dos formulários para preenchimento dos relatórios

### ISSUE THREAD

**Issue by OmarGhoche** [pontus-vision/pontus-vision#15]
**Resumo:**
Design dos formulários para preenchimento dos relatórios

**Eu quero:**
Personalizar os formulários dos relatórios LGPD no budibase. Analisando necessidade de funis (dependendo do tipo de resposta) e visão por área (caso necessidade).

**Para que:**
Boa experiência do usuário e inteligência para o preenchimento.

**Comment by OmarGhoche** [comment]
@AmandaMozena:

Budibase
Em resumo: temos que refletir o sharepoint neste aplicativo
Objetivo: que seja parte da nossa plataforma, onde os clientes poderão cadastrar os dados nos relatórios e ver os indicadores destes dados
Intuito: que tenha um bom UX

Próximos Passos (aqui estou listando tudo o que precisamos fazer)

Subir todas as listas que temos > usamos modelo Sunnyvale
Começar a colocar design nos formulários, pensando na usabilidade do usuário

Se a questão for possível ter funil procurar forma de aplicar. Por exemplo, questão da lista de mapeamento de processo, que se o usuário colocar na fonte de dados ‘Outros’, ela tem que descrever na outra pergunta qual é a fonte. Assim, podemos programar De aparecer esta pergunta só se tiver a resposta Outro.

Verificar se é possível ter tipo de visualização, como o Leo fez para a Porsche (aqueles botões de TI / Jurídico)

Gerar dados fictícios para colocarmos nas listas

Gerar os relatórios que façam sentido (trabalho em conjunto)

Implementar o fluxo de automação (para as listas de mapeamento de processos e fonte de dados > como fizemos com a Sunnyvale)

**Comment by pontusvision** [comment]
Falta a logica de ocultar os campos de LIA se a base legal nao for Legitimo interesse
