### ISSUE TITLE
Consolidar Grafana e Budibase

### ISSUE THREAD

**Issue by OmarGhoche** [pontus-vision/pontus-vision#17]
**Resumo:**
Consolidar Grafana e Budibase

**Eu quero:**
Verificar melhor forma de consolidar o Grafana e Budibase.

**Para que:**
Melhoria do produto. Para clientes da Pontus conseguirem em um único ambiente inserirem as informações dos relatórios e terem a visualização consolidada destes dados, com indicadores e as demais informações e dados do Grafana, que já estão prontos.

**Funcionalidades:**
> Relatório de Impacto à Proteção de Dados (RIPD)
> Legítimo Interesse (LIA)
> Avisos de Privacidade
> Consentimentos
> Riscos de Segurança
> Mitigações de Riscos de Segurança
> Incidentes de Segurança
> Políticas de Privacidade
> Fontes de Dados
> DSAR
> Treinamentos

**Comment by AmandaMozena** [comment]
Budibase não foi selecionado como componente para nosso gestor de formulários. Vamos seguir com Webiny.
