### ISSUE TITLE
Instalar imagem docker da Oracle - Versão 12.2

### ISSUE THREAD

**Issue by AmandaMozena** [pontus-vision/pontus-vision#35]
**Resumo:**
Instalar imagem docker da Oracle - Versão 12.2

**Como um:**
Pontus Vision Engineer

**Eu quero:**
Instalar a imagem docker da Oracle - Versão 12.2

**Para que:**
Instalação da plataforma na máquina da MPF.

**Comment by pontusvision** [comment]
..
