### ISSUE TITLE
Docker Swarm

### ISSUE THREAD

**Issue by thiagocpv** [pontus-vision/pontus-vision#4]
Olá, existe uma versão para docker swarm?
obrigado.

**Comment by pontusvision** [comment]
Hi Thiago, 

  Apologies for the delay in replying.  We have decided to focus on k3s instead of docker swarm; however, it should be easy to start the environment on docker swarm instead.  Please let us know whether you need any assistance.
  
  Kind Regards,
  
       Pontus Vision Team.
