### ISSUE TITLE
Corrigir /home/agrecords ERROR 405 na DEMO na parte de "Detalhes dos titulares v3"

### ISSUE THREAD

**Issue by AmandaMozena** [pontus-vision/pontus-vision#50]
**Resumo:**
Corrigir /home/agrecords ERROR 405 na DEMO na parte de "Detalhes dos titulares v3"

**Como:**
Pontus Engineer

**Eu quero:**
Corrigir /home/agrecords ERROR 405 na DEMO na parte de "Detalhes dos titulares v3"

**Para que:**
Funcionamento correto da demo da Pontus Vision, refletindo o que possuímos em uso com os clientes, em produção.

**Comment by OmarGhoche** [comment]
as mudanças já foram feita na demo local, basta revisão do @pontusvision para enviar para o Github
