### ISSUE TITLE
Melhorias demo - versão Sunnyvale

### ISSUE THREAD

**Issue by AmandaMozena** [pontus-vision/pontus-vision#51]
**Resumo:**
Melhorias demo - versão Sunnyvale

**Como:**
Pontus Engineer

**Eu quero:**
Realizar melhorias na demo da Pontus, para refletir o que temos no cliente Sunnyvale. Um ponto é o botão azul do relatório DSAR.

Fazer pv local antes de realizar pull request, para não ter contaminação

**Para que:**
Funcionamento correto da demo da Pontus Vision, refletindo o que possuímos em uso com os clientes, em produção.

**Comment by OmarGhoche** [comment]
censurar as coisas da Sunnyvale localmente (grafana.db) antes de mandar para GitHub!

**Comment by OmarGhoche** [comment]
as mudanças já foram feita na demo local, basta revisão do @pontusvision para enviar para o Github
