### ISSUE TITLE
R&D Azure

### ISSUE THREAD

**Issue by AmandaMozena** [pontus-vision/pontus-vision#66]
**Resumo:**
R&D Azure

**Como um:**
Pontus Vision Engineer

**Eu quero:**
1. Realizar R&D para ambiente da Azure, levantando os prós e contras e comparando com a AWS.
2. Realizar PK

**Para que:**
Implementar a plataforma em Cloud

**Comment by OmarGhoche** [comment]
estamos stuck (atolados/presos) em uma parte do código onde não conseguimos conectar grafos que estão em partições lógicas (Partition Key - pk) distintas [esse conceito é próprio do Azure Cosmos DB]. Postei várias PERGUNTAS em fóruns online (StackOverflow e Oficial da Azure) e enquanto aguardo alguma resposta ou ajuda estou lendo mais documentação e outros artigos!

**Comment by OmarGhoche** [comment]
Links sobre Azure Cosmos DB pk

https://learn.microsoft.com/en-us/answers/questions/1286272/how-to-add-an-edge-between-2-vertices-in-different?ns-enrollment-type=Collection&ns-enrollment-id=m1ekix6ood640j

https://learn.microsoft.com/en-us/azure/cosmos-db/gremlin/partitioning?ns-enrollment-type=Collection&ns-enrollment-id=m1ekix6ood640j

https://learn.microsoft.com/en-us/azure/cosmos-db/gremlin/quickstart-java?ns-enrollment-type=Collection&ns-enrollment-id=m1ekix6ood640j

https://learn.microsoft.com/en-us/azure/cosmos-db/partitioning-overview?ns-enrollment-type=Collection&ns-enrollment-id=m1ekix6ood640j

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/synthetic-partition-keys?ns-enrollment-type=Collection&ns-enrollment-id=m1ekix6ood640j

**Comment by OmarGhoche** [comment]
Com relação ao _pricing_ do serviço **Azure Cosmos DB Gremlin API** ... segue abaixo as estimativas para 3 categorias (Standard Provisioned, Autoscale Provisioned e Serverless):

[standard-provisioned.xlsx](https://github.com/pontus-vision/pontus-vision/files/11501489/standard-provisioned.xlsx)
[autoscale-provisioned.xlsx](https://github.com/pontus-vision/pontus-vision/files/11501490/autoscale-provisioned.xlsx)
[serverless.xlsx](https://github.com/pontus-vision/pontus-vision/files/11501491/serverless.xlsx)
