### ISSUE TITLE
Cancelar acessos Omar

### ISSUE THREAD

**Issue by AmandaMozena** [pontus-vision/pontus-vision#68]
**Como um:**
Adm Pontus

**Eu quero:**
Cancelar acessos do ex-colaborador Omar
 
**Para que:**
Não tenha mais acesso aos ambientes da Pontus Vision.

**Locais para cancelar o acesso:**
- Pontus Office 365 (sharepoint/ email/power automate, etc)
- Pontus Slack
- Pontus Github
- Pontus Trello

**Cancelar acesso através dos clientes:**
- Sunny VPN
- Sunny Sharepoint
- Sunny Githhub
- Sunny trello
- Sunny slack
- Porsche Office 365 (Sharepoint / power automate)

**Comment by pontusvision** [comment]
disabled office access + Slack + converted to outside contributor on github

**Comment by AmandaMozena** [comment]
Solicitado à Sunnyvale que remova os acessos do Trello, Slack, Sharepoint e Reset na VPN.
Eles não possuem github.

Quanto a Porsche, Omar não tinha acesso. Usava credenciais Amanda.

**Comment by AmandaMozena** [comment]
Pontus Trello removido o acesso.

**Comment by AmandaMozena** [comment]
Sunnyvale reset na VPN e cancelado o acesso do sharepoint
